### ISSUE TITLE
Markdown to HTML issues for OSLC-OP Specs

### ISSUE THREAD

**Issue by jamsden** [oslc-op/oslc-specs#583]
- [ ] Level 1 headings are followed by a horizontal rule that may not be acceptable to OASIS
- [ ] Need to have some means of indicating conformance text, possibly <span class='conformance'>...</span> is sufficient
- [ ] Need a way to add example text that formats properly for OASIS, possibly can be added between `example text` or embedded in:
```
This is 
a multi-line
example
```
- [ ] Probably should add more variables in the template.html for the respecConfig variables that are going to be regularly updated
- [ ] Need some means of denoting normative and non-normative content

**Comment by berezovskyi** [comment]
> Level 1 headings are followed by a horizontal rule that may not be acceptable to OASIS


https://oslc-op.github.io/oslc-specs/specs/core/oslc-core.html#motivation has those hr's!

Otherwise:

1. Removing the `--section-divs` from the command would use bare h1 for level one headings, instead of also using `<section>`. ReSpec hr's each section. **You will lose nice TOC if you do this!**
2. Replace the `hr {}` CSS rule in the header with this:
```css
      @media only screen {
        hr {
          display: none;
        }
      }
```

**Comment by berezovskyi** [comment]
> Need a way to add example text that formats properly for OASIS, possibly can be added between example text or embedded in

Add this bit of CSS in the HEAD:

```css
      body#respecDocument pre,
      body#respecDocument code {
        color: black;
        font-family: ui-monospace, Menlo, Monaco, "Cascadia Mono", "Segoe UI Mono", "Roboto Mono", "Oxygen Mono",
          "Ubuntu Monospace", "Source Code Pro", "Fira Mono", "Droid Sans Mono", "Courier New", monospace;
        font-weight: 400;
      }
```

This will reset a red bold typewriter font to the normal black best mono font that is installed by default on mac, win, linux.
